"""
Project Euler Problem 2

Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which
do not exceed four million.
"""

def fibonacci(N):
    # Start the sequence with two seed values
    sequence = [0, 1]
    
    for n in range(2, N, 1):
        sequence.append(sequence[n-1] + sequence[n-2])
    
    return sequence

accumulator = 0

seq = fibonacci(150)

for value in seq:
    if value < 4000000 and value % 2 == 0:
        accumulator = accumulator + value

print accumulator
